### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [Bike/introspect-environment#1]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by Bike** [comment]
It took me a minute to realize this was referring to the test system. I don't know if quicklisp actually needs that metadata, but I went ahead and added it anyway.
