### ISSUE TITLE
Reflect changes in cl-parametric-types for typexpand

### ISSUE THREAD

**Issue by guicho271828** [Bike/introspect-environment#3]
https://github.com/cosmos72/cl-parametric-types/blob/05dbd839172d6eb6dfc78cc4e53238f95c0c7369/lang/typexpand.lisp#L24

**Comment by Bike** [comment]
Are there any available `variable-type`, `function-type`, etc.?

**Comment by guicho271828** [comment]
I don't think so, I am only suggesting the addition of typexpand

**Comment by Bike** [comment]
OK, I'll put this in later today probably, since people want it

**Comment by Bike** [comment]
There you go. I don't have these implementations around for testing, though.

**Comment by guicho271828** [comment]
thanks!
